Feat/add messages stats
OurvoiceService/ourvoice-php pull request #10
Opened 2023-09-13 08:12 UTC by asiedu-kev

2023-09-13 23:20 UTC, shadonet requested changes
A class name should always be in singular

2023-09-13 23:20 UTC, shadonet commented on src/Resources/Messages.php
>              Common\HttpClient::REQUEST_GET,
You better remove Common class hier

2023-09-13 23:20 UTC, shadonet commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
Response header has never been used. So, why return it from http client?

2023-09-13 23:56 UTC, asiedu-kev commented on src/Resources/Messages.php
>              Common\HttpClient::REQUEST_GET,
Hum why, it's on the importation.and it's not the first time, we're using it like that since the beginning

2023-09-13 23:58 UTC, asiedu-kev commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
I didn't use it, I skipped it so as not to declare a variable and not to use it, the function returns it by default doc it's a way of avoiding retrieving the variable that is returned.

2023-09-13 23:59 UTC, asiedu-kev commented
> A class name should always be in singular

Hum...it's like that since beginning, anyway noted ..for next time it will take into account or I change all right now ?

2023-09-14 00:03 UTC, shadonet commented on src/Resources/Messages.php
>              Common\HttpClient::REQUEST_GET,
Just use HttpClient, you've already imported it

2023-09-14 00:05 UTC, asiedu-kev commented on src/Resources/Messages.php
>              Common\HttpClient::REQUEST_GET,
Okay

2023-09-14 00:05 UTC, shadonet commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
Why the function is returning it by default if it has never been used?

2023-09-14 00:06 UTC, shadonet commented
> > A class name should always be in singular
> 
> 
> 
> Hum...it's like that since beginning, anyway noted ..for next time it will take into account or I change all right now ?

In the next major release

2023-09-14 00:09 UTC, asiedu-kev commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
I don't think but we can't predict if it should or not...by default the template we have followed do it like that and we chwnge the function, we should update all the code now..

2023-09-14 00:12 UTC, asiedu-kev commented
> > > A class name should always be in singular
> > 
> > 
> > Hum...it's like that since beginning, anyway noted ..for next time it will take into account or I change all right now ?
> 
> In the next major release

Okay...it's what I were talking about...no documentation on things and day by day things are changing just like that, but it’s you who validated things at beginning…PS: Nothing personally but I think it could help us be happy to work when things are goodly done.

2023-09-14 00:15 UTC, shadonet commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
We followed it for inspiration not for copy pasta work and nothing guaranteed that they are following the best code standards

2023-09-14 00:16 UTC, asiedu-kev commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
So I update it in all functions ?... Okay tomorrow then

2023-09-14 00:18 UTC, shadonet commented on src/Resources/Messages.php
> +        [$responseStatus,, $responseBody] = $this->httpClient->performHttpRequest(
Okay! No problem champ

2023-09-14 14:32 UTC, shadonet commented
> > > > A class name should always be in singular
> > > 
> > > 
> > > Hum...it's like that since beginning, anyway noted ..for next time it will take into account or I change all right now ?
> > 
> > 
> > In the next major release
> 
> Okay...it's what I were talking about...no documentation on things and day by day things are changing just like that, but it’s you who validated things at beginning…PS: Nothing personally but I think it could help us be happy to work when things are goodly done.

Nothing is static in this world. And the code you wrote today will be outdated tomorrow. And there is always a room for improvement. You have to know that the code you wrote for the MVP will change as the time evolve. I even don't know why you are complaining. The life is not about not making mistakes, it is about fixing your mistakes in the next iterations.

2023-09-14 14:59 UTC, shadonet requested changes
NSC

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Account.php
> -    public function __construct(Common\HttpClient $httpClient)
Remove also `use Ourvoice\Common;` from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Medias.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Messages.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Numbers.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Steps.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Subscriptions.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Voices.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 14:59 UTC, shadonet commented on src/Resources/Webhooks.php
>  use Ourvoice\Common;
Remove also use Ourvoice\Common; from line 5.

2023-09-14 18:32 UTC, shadonet approved these changes

2023-09-14 18:33 UTC, merged